title: Hariom Narang's Pages
author: narang99
subtitle: engineering anything and everything

url: "https://pages.narang99.in"

footer_only_homepage: true
footer_url: "https://github.com/narang99"
footer_text: "github"

profile-picture: assets/duck-with-kinfe.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
  style: compressed
  sass_dir: _sass

highlighter: rouge

navbar:
 - name: "About"
   link: "about"
